#+TITLE: Configuration Files
#+AUTHOR: Ethan Johnston
#+OPTIONS: toc:nil


* About
+ This repository is mostly just for the purposes of hosting my spacemacs config.
+ Just in case I'll document any of the additional keybindings or functionality that I've added.
* Spacemacs
** Set up
I've had a better time of things using the develop branch, so I set things up using the following. 
   #+begin_src shell
rm -rf ~/.emacs.d
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d   
cd ~
git checkout develop
git pull origin develop 
   #+end_src
** Defaults
I've enabled a lot of the useful layers that aren't automatically
turned on (auto-completion, spellcheck, syntax check, etc.). Outside of this I've enabled some QOL features that I
personally prefer having on like line numbers in code files and slanted style for the modeline.
** User Config
*** Org-mode
Most of my config is for org-mode so far. One thing I really like is having syntax highlighting 
in the pdf output from org files. You can achieve this with the following snippet I got from a TA of mine.
#+begin_src elisp
(setq org-latex-listings 'minted
          org-latex-packages-alist '(("" "minted"))
          org-latex-pdf-process
          '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
            "biber %b"
            "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")
)
#+end_src
If for some reason you are looking to use this .spacemacs setup, be aware
that minted has dependencies and the above will most likely crash your latex export if you don't have them. You'll want
to make sure you've got python and the pygments package installed (see [[http://pygments.org/download/][installation]]). If that doesn't work
the issue is with your latex packages not with emacs itself (as I've learned the hard way).

I do a lot of writing in org mode, so I've got it set up to linewrap once it overflows on the buffer instead of the window. This is achieved by pasting this anywhere in user-config.
#+begin_src elisp
(add-hook 'org-mode-hook 'visual-line-mode)
#+end_src
*** React and Vue
My configuration includes and uses rjsx-mode for all js files, if you want it to narrow the scope of when it activates
then change the following line to be a more precise pattern. I've also added vue-mode which I've found is a little lacking
so I turn web-mode for .vue files instead.
#+begin_src elisp
;; activate frontend modes as follows
(add-to-list 'auto-mode-alist '("\\.js\\'" . react-mode))
(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))
#+end_src
*** Darkroom
I do a lot of writing in emacs aside from programming itself. To make it easier to focus I have the package darkroom included in my additional packages section. I created a toggle for this via the following snippet. (it just centres the text and zooms in)
#+begin_src elisp
;; darkroom hotkey
(spacemacs|add-toggle darkroom-mode
    :status darkroom-mode
    :on (darkroom-mode)
    :off (darkroom-mode -1)
    :documentation "Turn on darkroom mode"
    :evil-leader "zd")
#+end_src
*** Additional Keybindings
+ ~(SPC e ')~ opens the eshell in your current buffer.
+ ~(SPC m ')~ opens the multi-term in your current buffer.
+ ~(SPC y r)~ will reload your snippets.
+ ~(SPC y n)~ will open a new snippet.
+ ~(SPC z d)~ will toggle darkroom.
